In [82]:
import tensorflow as tf
import BHDVCS 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from scipy.optimize import curve_fit
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
func = BHDVCS.BHDVCS()

In [83]:
class DvcsData(object):
    def __init__(self, df):
        self.X = df.loc[:, ['phi_x', 'k', 'QQ', 'x_b', 't', 'F1', 'F2', 'ReH', 'ReE', 'ReHtilde', 'dvcs']]
        self.XnoCFF = df.loc[:, ['phi_x', 'k', 'QQ', 'x_b', 't', 'F1', 'F2', 'dvcs']]
        self.y = df.loc[:, 'F']
        self.Kinematics = df.loc[:, ['k', 'QQ', 'x_b', 't']]
        self.erry = df.loc[:, 'errF']
        
    def __len__(self):
        return len(self.X)
    
    def getSet(self, setNum, itemsInSet=36):
        pd.options.mode.chained_assignment = None
        subX = self.X.loc[setNum*itemsInSet:(setNum+1)*itemsInSet-1, :]
        subX['F'] = self.y.loc[setNum*itemsInSet:(setNum+1)*itemsInSet-1]
        subX['errF'] = self.erry.loc[setNum*itemsInSet:(setNum+1)*itemsInSet-1]
        pd.options.mode.chained_assignment = 'warn'
        return DvcsData(subX)
    
    def sampleY(self):
        return np.random.normal(self.y, self.erry)

In [84]:
df = pd.read_csv('data.csv')
x_data = df.loc[:, ['k', 'QQ', 'x_b', 't']]
y_data = df.loc[:, ['ReH', 'ReE', 'ReHtilde']]

In [85]:
dat = df.loc[:, ['phi_x', 'QQ', 'x_b', 't', 'k', 'F1', 'F2', 'dvcs']]

F = df.loc[:,['F']]
F = F.to_numpy()

dayta = np.zeros(36)
g = 0
def setData(dat, i):
    global dayta
    global g
    g = i
    dayta = dat


def los(y_true, y_pred):
    print((y_true[0] + y_true[1]+ y_true[2])/3)
    #dat = data[g:g+1].to_numpy().transpose()    
    
    #loss1 = np.sum(abs(func.TotalUUXS_curve_fit(dat, y_pred[0], y_pred[1], y_pred[2]) - F[0:36].transpose()))
    loss1 = np.sum(abs(dayta - F[g*36:g*36+36].transpose()))
    loss2 = abs(abs(((y_true[0] + y_true[1]+ y_true[2])/3))-abs(((y_pred[0] + y_pred[1]+ y_pred[2])/3)))
    
    return (loss1**3)*loss2
    
    #return (((pErr(y_pred[0], y_true[0]) + pErr(y_pred[1], y_true[1]) +pErr(y_pred[2], y_true[2]))/errF[g])**2)*((tot/errF[g])**2)

In [86]:
x_data, y_data = x_data/255.0, y_data/255.0
print(x_data)

            k        QQ       x_b         t
0    0.014706  0.006824  0.001706 -0.001494
1    0.014706  0.006824  0.001706 -0.001494
2    0.014706  0.006824  0.001706 -0.001494
3    0.014706  0.006824  0.001706 -0.001494
4    0.014706  0.006824  0.001706 -0.001494
..        ...       ...       ...       ...
535  0.030392  0.010324  0.001353 -0.001416
536  0.030392  0.010324  0.001353 -0.001416
537  0.030392  0.010324  0.001353 -0.001416
538  0.030392  0.010324  0.001353 -0.001416
539  0.030392  0.010324  0.001353 -0.001416

[540 rows x 4 columns]


In [87]:
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(4,)))

model.add(tf.keras.layers.Dense(128, activation='tanh'))
model.add(tf.keras.layers.Dense(32, activation='tanh'))
model.add(tf.keras.layers.Dense(100, activation='relu'))

model.add(tf.keras.layers.Dense(3))
    

    
    
mod = tf.keras.models.Sequential()
mod.add(tf.keras.Input(shape=(4,)))

mod.add(tf.keras.layers.Dense(128, activation='tanh'))
mod.add(tf.keras.layers.Dense(32, activation='tanh'))
mod.add(tf.keras.layers.Dense(100, activation='relu'))

mod.add(tf.keras.layers.Dense(3))
    
dat = pd.read_csv('data.csv')
for i in range(15):
    
    for j in range(10):
        print(i)
                        
        data = DvcsData(dat)
        set0 = data.getSet(i)
        
        setData(np.asarray(set0.sampleY()).T, i)
            
        x_data = dat.loc[:, ['k', 'QQ', 'x_b', 't']].to_numpy()[36*i:36*i+36]
        y_data = dat.loc[:, ['ReH', 'ReE', 'ReHtilde']].to_numpy()[36*i:36*i+36]
        
        if dat.loc[:, ['t']].to_numpy()[36*i:36*i+1][0] > -0.32391780000000003:
            model.compile(optimizer='adam', loss='mse')
            model.fit(x_data, y_data, epochs=10)
        else:
            mod.compile(optimizer='adam', loss='mse')
            mod.fit(x_data, y_data, epochs=10)

        

0
Epoch 1/10
2/2 [==============================] - 0s 724us/step - loss: 1000.2222
Epoch 2/10
2/2 [==============================] - 0s 1ms/step - loss: 980.4666
Epoch 3/10
2/2 [==============================] - 0s 997us/step - loss: 963.0334
Epoch 4/10
2/2 [==============================] - 0s 2ms/step - loss: 946.6041
Epoch 5/10
2/2 [==============================] - 0s 1ms/step - loss: 929.6514
Epoch 6/10
2/2 [==============================] - 0s 997us/step - loss: 912.8425
Epoch 7/10
2/2 [==============================] - 0s 995us/step - loss: 895.7913
Epoch 8/10
2/2 [==============================] - 0s 1ms/step - loss: 878.6370
Epoch 9/10
2/2 [==============================] - 0s 1ms/step - loss: 860.9387
Epoch 10/10
2/2 [==============================] - 0s 1ms/step - loss: 842.7435
0
Epoch 1/10
2/2 [==============================] - 0s 1ms/step - loss: 824.4614
Epoch 2/10
2/2 [==============================] - 0s 499us/step - loss: 806.2454
Epoch 3/10
2/2 [====================

In [88]:
x_data = dat.loc[:, ['k', 'QQ', 'x_b', 't']].to_numpy()[0:541:36]
x_data, y_data = x_data*255.0, y_data*255.0

In [89]:
dat = pd.read_csv('data.csv')
data = DvcsData(dat)
set0 = data.getSet(0)
        
setData(np.asarray(set0.XnoCFF).T, 0)
        
        
x_train = np.asarray(set0.Kinematics).T # have to take transpose to get everything to work
y_sample = np.asarray(set0.sampleY())


x_data = dat.loc[:, ['k', 'QQ', 'x_b', 't']].to_numpy()[0:541:36]

    
y_data = dat.loc[:, ['ReH', 'ReE', 'ReHtilde']].to_numpy()[36*0:36*0+4]


In [94]:
g = 14
tmean = -0.32391780000000003
x_data = pd.read_csv('data.csv')
y_data = pd.read_csv('data.csv')
#,'dvcs'
#k,QQ,x_b,t,phi_x,F,errF,F1,F2,dvcs
x_data = x_data.drop(columns=['#Set','index','F','errF','ReH','ReE','ReHtilde','phi_x', 'F1', 'F2', 'dvcs'])
y_data = y_data.drop(columns=['#Set','index','k','QQ','x_b','phi_x','F','errF','F1','F2','dvcs'])


x_group_1 = x_data[x_data['t'] < tmean]
x_group_2 = x_data[x_data['t'] > tmean]


y_group_1 = y_data[y_data['t'] < tmean]
y_group_1 = y_group_1.drop(columns=['t'])

y_group_2 = y_data[y_data['t'] > tmean]
y_group_2 = y_group_2.drop(columns=['t'])



x1 = pd.DataFrame(x_group_1.loc[0:36*g+36:36]).to_numpy()
y1 = pd.DataFrame(y_group_1.loc[0:36*g+36:36]).to_numpy()
x2 = pd.DataFrame(x_group_2.loc[0:36*g+36:36]).to_numpy()
y2 = pd.DataFrame(y_group_2.loc[0:36*g+36:36]).to_numpy()

x1, x2 = x1/255.0, x2/255.0



print(mod.predict(x2))
print(y2)

print(model.predict(x1))
print(y1)


[[  9.127459  -40.279648    5.0899034]
 [  9.1255045 -40.271       5.0888247]
 [  9.164233  -40.44172     5.1106625]
 [  9.162304  -40.43318     5.1095967]
 [  9.194127  -40.573383    5.127611 ]
 [  9.200547  -40.60177     5.131159 ]
 [  9.230062  -40.73176     5.1478915]
 [  9.2364    -40.759773    5.1513944]]
[[  7.22424 -47.2242    4.01347]
 [  7.65272 -47.6527    4.25151]
 [  7.22424 -47.2242    4.01347]
 [  7.65272 -47.6527    4.25151]
 [  6.99014 -46.9901    3.88341]
 [  7.22424 -47.2242    4.01347]
 [  6.99014 -46.9901    3.88341]
 [  7.22424 -47.2242    4.01347]]
[[  5.109326  -33.56393     2.8156345]
 [  5.114279  -33.596817    2.8183656]
 [  5.1392546 -33.762524    2.8322408]
 [  5.173466  -33.989525    2.8512065]
 [  5.1639776 -33.92656     2.845976 ]
 [  5.1978407 -34.151253    2.8647501]
 [  5.2219653 -34.311317    2.8781536]]
[[ 13.0554  -53.0554    7.25302]
 [ 12.5549  -52.5549    6.97494]
 [ 12.5549  -52.5549    6.97494]
 [ 11.7411  -51.7411    6.52283]
 [ 12.5549  -52.