## Outputs for TVA1UU.py

In [1]:
%load_ext autoreload
%autoreload 2

In [10]:
import numpy as np
import pandas as pd

In [3]:
from TVA1_UU import TVA1_UU

In [4]:
test = TVA1_UU()

In [13]:
d = pd.read_csv('dvcs_psuedo.csv')

In [20]:
t = np.array(d.loc[:, ['phi_x', 'k', 'QQ', 'x_b', 't', 'F1', 'F2', 'dvcs']])

In [21]:
t

array([[0.00000e+00, 3.75000e+00, 1.74013e+00, ..., 4.98060e-01,
        6.85790e-01, 1.22881e-02],
       [1.00000e+01, 3.75000e+00, 1.74013e+00, ..., 4.98060e-01,
        6.85790e-01, 1.22881e-02],
       [2.00000e+01, 3.75000e+00, 1.74013e+00, ..., 4.98060e-01,
        6.85790e-01, 1.22881e-02],
       ...,
       [3.30000e+02, 7.75000e+00, 2.63258e+00, ..., 5.12913e-01,
        7.14810e-01, 1.22881e-02],
       [3.40000e+02, 7.75000e+00, 2.63258e+00, ..., 5.12913e-01,
        7.14810e-01, 1.22881e-02],
       [3.50000e+02, 7.75000e+00, 2.63258e+00, ..., 5.12913e-01,
        7.14810e-01, 1.22881e-02]])

In [22]:
test.TotalUUXS(t, 1., 1., 1.)

<tf.Tensor: shape=(540,), dtype=float64, numpy=
array([0.16711215, 0.16067786, 0.14386318, 0.12212089, 0.10037232,
       0.08136925, 0.06598486, 0.05406195, 0.04505388, 0.03835542,
       0.03343253, 0.02985426, 0.02728612, 0.02547269, 0.02422046,
       0.02338447, 0.02285906, 0.02257194, 0.02248087, 0.02257194,
       0.02285906, 0.02338447, 0.02422046, 0.02547269, 0.02728612,
       0.02985426, 0.03343253, 0.03835542, 0.04505388, 0.05406195,
       0.06598486, 0.08136925, 0.10037232, 0.12212089, 0.14386318,
       0.16067786, 0.24809985, 0.2357501 , 0.20497647, 0.16808723,
       0.13403023, 0.10625538, 0.08490319, 0.06891371, 0.0570608 ,
       0.04830047, 0.04183077, 0.03705958, 0.03355535, 0.03100399,
       0.02917668, 0.02790752, 0.02707881, 0.02661178, 0.02646104,
       0.02661178, 0.02707881, 0.02790752, 0.02917668, 0.03100399,
       0.03355535, 0.03705958, 0.04183077, 0.04830047, 0.0570608 ,
       0.06891371, 0.08490319, 0.10625538, 0.13403023, 0.16808723,
       0.20497

In [23]:
from ROOT import gROOT

gROOT.LoadMacro('F.C')
from ROOT import F
f = F()

Welcome to JupyROOT 6.22/00


ImportError: cannot import name 'F' from 'ROOT' (/usr/local/Cellar/root/6.22.00/lib/root/ROOT/__init__.py)